import { generateSound } from './audioService';

export const notesData = [
  {
    colour: '#05EFFF',
    width: 50,
    height: 50,
    top: 20,
    left: 15,
    frequency: 330,
    name: 'E',
    fill: 'red',
    callback() { return generateSound(this.frequency); },
  },
  {
    colour: '#05EFFF',
    width: 50,
    height: 50,
    top: 20,
    left: 75,
    frequency: 247,
    name: 'H',
    fill: 'red',
    callback() { return generateSound(this.frequency); },
  },
  {
    colour: '#05EFFF',
    width: 50,
    height: 50,
    top: 20,
    left: 135,
    frequency: 196,
    name: 'G',
    fill: 'red',
    callback() { return generateSound(this.frequency); },
  },
  {
    colour: '#05EFFF',
    width: 50,
    height: 50,
    top: 20,
    left: 195,
    frequency: 147,
    name: 'D',
    fill: 'red',
    callback() { return generateSound(this.frequency); },
  },
  {
    colour: '#05EFFF',
    width: 50,
    height: 50,
    top: 20,
    left: 255,
    frequency: 110,
    name: 'A',
    fill: 'red',
    callback() { return generateSound(this.frequency); },
  },
  {
    colour: '#05EFFF',
    width: 50,
    height: 50,
    top: 20,
    left: 315,
    frequency: 82,
    name: 'E',
    fill: 'red',
    callback() { return generateSound(this.frequency); },
  },
];
